build-job:
  stage: build
  script:
    - npm install
    - npm run build

run-tests:
  stage: test
  script:
    - echo "We should test here"

deploy-prod:
  stage: deploy
  script:
    - ssh pixel@192.168.178.10 'rm -r /home/pixel/test_dump/*'
    - sftp pixel@192.168.178.10:/home/pixel/test_dump <<< $'put dist/*'
  environment: production
