build-job:
  stage: build
  script:
    - npm install
    - npm run build
    - ssh pixel@192.168.178.10 'rm -r /home/pixel/test_dump/*'
    - sftp pixel@192.168.178.10:/home/pixel/test_dump <<< $'put dist/*'
