build-job:
  stage: build
  script:
    - npm install
    - npm run build

run-tests:
  stage: test
  script:
    - echo "We should test here"

deploy-prod:
  stage: deploy
  script:
    - ssh pixel@jobs.server.de '/home/pixel/test_dump/*'
    - sftp pixel@jobs.server.de:/home/pixel/test_dump <<< $'put dist/*'
  environment: production
